// Generated with gyb. Do not edit.

import Swift

public protocol Initiable {
    init()
}

extension Array: Initiable {}
extension ArraySlice: Initiable {}
extension Unicode.ASCII.Parser: Initiable {}
extension Bool: Initiable {}
extension ContiguousArray: Initiable {}
extension Dictionary: Initiable {}
extension EmptyCollection: Initiable {}
extension EmptyCollection.Iterator: Initiable {}
extension Float: Initiable {}
extension Double: Initiable {}
extension Float80: Initiable {}
extension Hasher: Initiable {}
extension SystemRandomNumberGenerator: Initiable {}
extension Set: Initiable {}
extension UInt: Initiable {}
extension UInt8: Initiable {}
extension UInt8.SIMD2Storage: Initiable {}
extension UInt8.SIMD4Storage: Initiable {}
extension UInt8.SIMD8Storage: Initiable {}
extension UInt8.SIMD16Storage: Initiable {}
extension UInt8.SIMD32Storage: Initiable {}
extension UInt8.SIMD64Storage: Initiable {}
extension Int: Initiable {}
extension Int8: Initiable {}
extension Int8.SIMD2Storage: Initiable {}
extension Int8.SIMD4Storage: Initiable {}
extension Int8.SIMD8Storage: Initiable {}
extension Int8.SIMD16Storage: Initiable {}
extension Int8.SIMD32Storage: Initiable {}
extension UInt16: Initiable {}
extension UInt16.SIMD2Storage: Initiable {}
extension UInt16.SIMD4Storage: Initiable {}
extension UInt16.SIMD8Storage: Initiable {}
extension UInt16.SIMD16Storage: Initiable {}
extension UInt16.SIMD32Storage: Initiable {}
extension UInt16.SIMD64Storage: Initiable {}
extension Int16: Initiable {}
extension Int16.SIMD2Storage: Initiable {}
extension Int16.SIMD4Storage: Initiable {}
extension Int16.SIMD8Storage: Initiable {}
extension Int16.SIMD16Storage: Initiable {}
extension Int16.SIMD32Storage: Initiable {}
extension Int16.SIMD64Storage: Initiable {}
extension UInt32: Initiable {}
extension UInt32.SIMD2Storage: Initiable {}
extension UInt32.SIMD4Storage: Initiable {}
extension UInt32.SIMD8Storage: Initiable {}
extension UInt32.SIMD16Storage: Initiable {}
extension UInt32.SIMD32Storage: Initiable {}
extension UInt32.SIMD64Storage: Initiable {}
extension Int32: Initiable {}
extension Int32.SIMD2Storage: Initiable {}
extension Int32.SIMD4Storage: Initiable {}
extension Int32.SIMD8Storage: Initiable {}
extension Int32.SIMD16Storage: Initiable {}
extension Int32.SIMD32Storage: Initiable {}
extension Int32.SIMD64Storage: Initiable {}
extension UInt64: Initiable {}
extension UInt64.SIMD2Storage: Initiable {}
extension UInt64.SIMD4Storage: Initiable {}
extension UInt64.SIMD8Storage: Initiable {}
extension UInt64.SIMD16Storage: Initiable {}
extension UInt64.SIMD32Storage: Initiable {}
extension UInt64.SIMD64Storage: Initiable {}
extension Int64: Initiable {}
extension Int64.SIMD2Storage: Initiable {}
extension Int64.SIMD4Storage: Initiable {}
extension Int64.SIMD8Storage: Initiable {}
extension Int64.SIMD16Storage: Initiable {}
extension Int64.SIMD32Storage: Initiable {}
extension Int64.SIMD64Storage: Initiable {}
extension StaticString: Initiable {}
extension String: Initiable {}
extension String.UnicodeScalarView: Initiable {}
extension Substring: Initiable {}
extension Substring.UnicodeScalarView: Initiable {}
extension Unicode.UTF8: Initiable {}
extension Unicode.UTF16: Initiable {}
extension Unicode.UTF32: Initiable {}
extension Unicode.UTF8.ForwardParser: Initiable {}
extension Unicode.UTF8.ReverseParser: Initiable {}
extension Unicode.UTF16.ForwardParser: Initiable {}
extension Unicode.UTF16.ReverseParser: Initiable {}
extension Unicode.UTF32.Parser: Initiable {}
